### PR TITLE
Fix clipboard support in Firefox 84+

### LINKED ISSUE #1364: Can't read the clipboard in firefox 84
## Error details

SurfingKeys: 0.9.68
Browser: firefox 84.0 in linux

## Context

In the latest stable version of firefox. The function `search selected with` does not work for the clipboard contents.
For example, if I press `sg`, it always searches the empty string in google when nothing is selected.
In the same computer, chrome works normally.

Related issue (maybe):
https://github.com/tridactyl/tridactyl/issues/3115

### PR DESCRIPTION
**Pull request by b0o**
Verified working on Linux in the following browser versions:

- Chrome 89.0.4356.6 dev
- Mozilla Firefox 85.0b4 (Developer Edition)
- Mozilla Firefox 84.0.1

Fixes #1364

### CODE REVIEW

**Comment by brookhong** [comment]
Thanks

File: content_scripts/clipboard.js [hunk 1]
```diff
@@ -32,6 +36,11 @@ function createClipboard() {
     };
 
     self.write = function(text) {
+        const cb = () => Front.showBanner("Copied: " + text);
+        if (typeof navigator.clipboard === 'object' && typeof navigator.clipboard.writeText === 'function') {
+          navigator.clipboard.writeText(text).then(cb);
```
Comment (bovine3dom) [inline content_scripts/clipboard.js:41]: I'm fairly sure this won't work on non-HTTPS pages - see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard - has anyone checked? : )

Comment (b0o) [reply content_scripts/clipboard.js:41]: Thanks for mentioning this, it actually did not cross my mind to test that. I will double check when I get a chance later today.

Comment (b0o) [reply content_scripts/clipboard.js:41]: Just got around to testing this and you are absolutely correct, @bovine3dom. 

Since @brookhong added a check in 116e52af5f552920db7582adc0272d8a8b086b5f to only enable this behavior if the browser is Firefox, at least there shouldn't be any regression in version 84 onward since it was totally broken. Until we can determine a better path forward that works on insecure sites as well, I think this should suffice most use cases.

Perhaps an additional check should be put in place to check the browser version is 84 or greater so that users on old versions don't have this functionality broken on insecure sites?

Comment (bovine3dom) [reply content_scripts/clipboard.js:41]: All you need to do in Firefox is execute the `clipboard` functions from the background script rather than content.

Surfingkeys will already be doing that sort of thing in lots of other places so it should be quite straightforward to send it a message from here and get the result back.
